### ISSUE TITLE
Do most of your users use mobile or desktop?

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/Unlock#10]
Hey @DebbieSUnlock!
For the prototype we would like to focus on _*either*_ desktop or mobile. Do you have a view on which this should be? 
Thanks!

**Comment by DebbieSUnlock** [comment]
@Jen-Harris 

For the prototype could we focus on desktop. Many thanks.

**Comment by Jen-Harris** [comment]
Perfect, thanks! 👍
