### ISSUE TITLE
Flowcharts

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/Unlock#11]
Hi @DebbieSUnlock 

As Jen said in the email, we recall you or someone else mentioning that you have some flowcharts for checking things like eligibility or DBS checks. If you could share these with us that would be great.

Thanks!

**Comment by DebbieSUnlock** [comment]
Hi @m4v15 

Here's the DBS flow chart we mentioned and also one for travelling to the US which you may find useful. 
[Filtering flowchart.pdf](https://github.com/InFact-coop/Unlock/files/1471727/Filtering.flowchart.pdf)
[Travel to the USA Flow Chart.docx](https://github.com/InFact-coop/Unlock/files/1471730/Travel.to.the.USA.Flow.Chart.docx)

D

**Comment by m4v15** [comment]
👍
