### ISSUE TITLE
Initial designs mocked up - feedback please!

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/Unlock#12]
Hey @DebbieSUnlock,
as mentioned on email we've made a start on mocking up some designs for the chatbot idea. I'll take you through screen by screen: 
1. We imagine the chat to be activated by a user clicking an icon in the bottom left hand side of the screen to prevent the chat interrupting people and causing frustration. **Icon is work in progress! Any ideas very welcome!**
![image](https://user-images.githubusercontent.com/26116988/32791019-e6b73478-c957-11e7-8651-5ec0d7c4082c.png)
![image](https://user-images.githubusercontent.com/26116988/32791356-ba4460ea-c958-11e7-84e8-d86475c00ea9.png)

2. The user could then be greeted by someone _*"Paul"*_ who introduces himself and _*could*_ tell a real story of someone who successfully travelled to the US after following the advice from Unlock.   
The user is then given a few options on where they may need advice. __It would be good to know the most popular searches to put in these boxes__
![image](https://user-images.githubusercontent.com/26116988/32791045-f5e256c6-c957-11e7-874d-3c507cbcb820.png) 
![image](https://user-images.githubusercontent.com/26116988/32791374-c6901fa6-c958-11e7-83a4-f3d5aa72bb30.png)

3.  The user would then go into a more 'chat' like interface. Where we've got to today is mocking up how it could look for options that _*aren't*_ travel. i.e. getting greeted and guided to the relevant info pages and given further topic choices that may be of interest
![image](https://user-images.githubusercontent.com/26116988/32791310-a2e66f56-c958-11e7-8b67-0d618e431358.png)
![image](https://user-images.githubusercontent.com/26116988/32791383-cebec790-c958-11e7-992b-5876affb8285.png)

  
  
__Things to note__: 
* At the moment we're following the colour scheme that is in place on the hub. we think this works really well but let us know what you think? 
* We'll be working on the user flow for the main (travel) conversation tomorrow 
* We're happy to mock a mobile flow as well if you would like - at the moment we have focused on desktop.
  
Please don't hold back with feedback! The more the better so we can build you a great prototype 💯

**Comment by DebbieSUnlock** [comment]
Hi @Jen-Harris 

This is looking fantastic. Can't believe that you've got so far already. 

1. Love the colours - think they work really well. 
2. Really like the idea of 'Paul' setting out his story. It somehow feels as though you're not just talking to a Bot. 

As far as the popular searches go, I think the following would be the most popular:-

- Criminal record checks
- Disclosure
- Insurance
- The ROA (not sure whether this wording works, maybe something slightly friendlier say 'spent or unspent'?
- Google effect
- Sexual offences

A mobile flow would be great but I'm conscious of time and more than happy for you to concentrate on desktop. I'm guessing that whatever we do on desktop could be adapted further down the line. 

Thanks so much. 

D
