### ISSUE TITLE
Presentation Tomorrow! :sparkles:

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/Unlock#28]
Hey @DebbieSUnlock,
We're in a really good place with the product today and can't wait to share it with you tomorrow! 

We feel this could be done over a call, if that's OK with you? We're very flexible on timings tomorrow, so when is best for you and the Unlock team?

**Comment by DebbieSUnlock** [comment]
Hey @Jen-Harris 

Fantastic news about the product. I'm so excited to see it. 

I'm happy for this to be done over the phone (I'm around all day so whenever's good for you). However, it wouldn't be possible to have the whole team around. Is this going to be a problem for you? 

Deb

**Comment by Jen-Harris** [comment]
Hey @DebbieSUnlock,

No problem about the team not being able to attend - you can show them all yourself! 

How is 2pm for you? 

Jen

**Comment by DebbieSUnlock** [comment]
Sounds perfect.

Look forward to speaking tomorrow.

Debs
